### ISSUE TITLE
@Collinshack 

### ISSUE THREAD

**Issue by ananasn** [Collinshack/lab7#1]
Отличная работа! Хорошее оформление. Работа принята, но обратите внимание на замечание ниже.

Есть небольшое замечание по заданию 2.
Условие ```1 от 4 и 1 от 18```  подразумевает что `1` - это первый столбец (не индекс, а порядок). Чтобы достать из файла первый столбец его берут по индексу `0`.

Если правильно поправить индексы то получится верный график. 
![Снимок экрана от 2024-03-23 14-08-57](https://github.com/Collinshack/lab7/assets/8919470/87c9555a-271c-44d5-b1c6-a91ad0098167)

**Comment by Collinshack** [comment]
Добрый день!
Большое спасибо вам за исправление.
Я исправил.
